drop table if exists public.confirmacoes_inauguracao cascade;
create table public.confirmacoes_inauguracao (
  id bigint generated by default as identity primary key,
  nome text not null check (char_length(nome) between 3 and 100),
  telefone text not null unique,
  presente boolean not null default true,
  acompanhantes integer not null default 0,
  observacoes text,
  criado_em timestamptz not null default now()
);
alter table public.confirmacoes_inauguracao enable row level security;
-- O site acessa o banco somente pela API segura da Vercel usando a service role.
create index confirmacoes_inauguracao_criado_em_idx on public.confirmacoes_inauguracao (criado_em desc);
