const $=id=>document.getElementById(id);let senhaPainel=sessionStorage.getItem('senhaPainel')||'';let dados=[];
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function formatTel(v){const n=String(v).replace(/\D/g,'');return n.length===11?`(${n.slice(0,2)}) ${n.slice(2,7)}-${n.slice(7)}`:v;}
function render(){const q=$('busca').value.toLowerCase();const lista=dados.filter(x=>(x.nome+' '+x.telefone).toLowerCase().includes(q));$('lista').innerHTML=lista.map(x=>`<tr><td>${esc(x.nome)}</td><td>${esc(formatTel(x.telefone))}</td><td>${esc(x.observacoes||'')}</td><td>${new Date(x.criado_em).toLocaleString('pt-BR')}</td><td class="no-print"><a class="small-btn" target="_blank" rel="noopener" href="https://wa.me/55${String(x.telefone).replace(/\D/g,'')}">Abrir</a></td></tr>`).join('');$('total').textContent=dados.length;}
async function carregar(){const msg=$('painelMsg');msg.textContent='Carregando...';try{const r=await fetch('/api/convidados',{headers:{'x-painel-senha':senhaPainel}});const d=await r.json();if(!r.ok)throw new Error(d.error||'Erro ao carregar');dados=d.convidados||[];render();$('atualizado').textContent=new Date().toLocaleTimeString('pt-BR');msg.textContent='';}catch(e){msg.className='message error';msg.textContent=e.message;if(r?.status===401)logout();}}
function loginOk(){sessionStorage.setItem('senhaPainel',senhaPainel);$('loginBox').classList.add('hidden');$('painel').classList.remove('hidden');carregar();setInterval(carregar,30000);}
function logout(){sessionStorage.removeItem('senhaPainel');location.reload();}
$('entrar').onclick=()=>{senhaPainel=$('senha').value.trim();if(!senhaPainel){$('loginMsg').textContent='Digite a senha.';return;}loginOk();};$('senha').addEventListener('keydown',e=>{if(e.key==='Enter')$('entrar').click();});$('sair').onclick=logout;$('busca').oninput=render;
$('exportar').onclick=()=>{const linhas=[['Nome','Telefone','Observação','Data'],...dados.map(x=>[x.nome,x.telefone,x.observacoes||'',new Date(x.criado_em).toLocaleString('pt-BR')])];const csv='\uFEFF'+linhas.map(l=>l.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(';')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='convidados-dirlaine.csv';a.click();URL.revokeObjectURL(a.href);};
if(senhaPainel)loginOk();
