-- Configuração segura da tabela de confirmações.
-- Este script não apaga a tabela nem os convidados existentes.

create table if not exists public.confirmacoes_inauguracao (
  id bigint generated by default as identity primary key,
  nome text not null check (char_length(nome) between 3 and 100),
  telefone text not null unique,
  presente boolean not null default true,
  acompanhantes integer not null default 0,
  observacoes text,
  criado_em timestamptz not null default now()
);

alter table public.confirmacoes_inauguracao
  enable row level security;

create index if not exists confirmacoes_inauguracao_criado_em_idx
  on public.confirmacoes_inauguracao (criado_em desc);

comment on table public.confirmacoes_inauguracao is
  'Confirmações de presença da inauguração da Dirlaine Souza Nail Designer.';
